最终会调用(2 2)，由于2不是一个函数，会报错。
